### PR TITLE
fix IE version detection in old IE

### LINKED ISSUE #2652: Browser.version reports undefined for IE 7 and below
The parsing of the UA String seems to be broken on mootools core 1.5.1 for old Internet Explorers. I checked with IE 6 and 7 and both report Browser.version "undefined". IE 8 and above (checked up to 11) work.

### PR DESCRIPTION
**Pull request by SergioCrisostomo**
Fixes #2652

### CODE REVIEW

**Comment by Ramon455k0** [comment]
The GT made a name for itself in the 1960s, and the nameplate returned to Ford for the 2005 and 2006 models. Since then, the vehicle has truly evolved into a supercar, evident by it’s $100,000+ price tag.
The company has made some changes to the third-generation GT, prioritizing handling and track capabilities in their 2017 model. The result? Not only one of Ford’s most impressive cars ever, but perhaps one of the most innovative cars to ever be released.
For more information about the [2017 Ford GT Wishlist](url=http://2017fordgtcar.com/2017-ford-gt-wishlist-features/) checkout.

**Comment by asussupport** [comment]
If you have any issue with the chrome support then you can visit us because we have all types of solutions. We are available 24*7 for your help. [Google customer service.](https://babasupport.org/software/google-play-music-customer-service/454)

**Comment by joanmelda** [comment]
It is undisputed that [Statistics Assignment Help Services](https://www.meldaresearch.com/statistics-assignment-help-service/) pose challenges for students because preparation takes into consideration a lot of details needed for [Statistics Writing Services](https://www.meldaresearch.com/statistics-assignment-help-service/) and in-depth knowledge on the topic in order to come up with a [Custom Statistics Coursework Writing Service](https://www.meldaresearch.com/statistics-assignment-help-service/).

**Comment by greatassignmenthelpuae** [comment]
Our **[Assignment Help Online](https://www.greatassignmenthelp.com/ae/)** writers are prepared enough for making the error-free assignments. They would doubtlessly meet the necessary models on account of the pack of innovative abilities they have. We guarantee to meet your writing rules so we could fulfill you and serve you with the best services. We esteem our clients and that is the explanation that our clients don't confront any sort of issue when they utilize our services. We guarantee you to furnish you with the best quality assignment and could never allow you to down. Our writers consistently write another substance that isn't duplicated from the other substance in this manner making your assignment of solid notoriety. That is the reason clients utilizing our services are free from stresses as we don't allow them to whine about our Assignment Help Online services.

**Pull request merged**
