### PR TITLE
fix #2434 - wrong calculation of offset

### LINKED ISSUE #2434: Wrong offset calculation because of floating point values
MooTools position calculation does not work correct if the element is position outside the screen if the page is centered within an document with an odd size.

The bounds in the getOffsets method are not rounded correctly.
If the offsets are absolute the rounding error does not affect the result but with a negative number the rounding error results in a wrong result.

Result should always be -250
Positive
Real calculation: 31.5-281.5 = -250
"Rounded" calculation: 31-281 = -250

Negative
Real: (-79.5)-170.5 = -250
Rounded: (-79)-170 = **-249**

Only affects webkit and gecko, ie and opera do not return floating point values.

See my testcase with a possible solution
With original MooTools: http://www.rrelmy.ch/mootools-position-bug/
With fixed MooTools: http://www.rrelmy.ch/mootools-position-bug/?fixed

### PR DESCRIPTION
**Pull request by rrelmy**
Fixes the bug described in #2434

Offsets are rounded correctly now

### CODE REVIEW

**Comment by rrelmy** [comment]
I have rebased the previous commit and written a test spec.

PhantomJS version 1.9.8 used by the karma runner is based on a webkit version released around 2011 before subpixel alignment was added to browsers.
I had to write the test around that. In the test a margin of 5.5 pixel is used, the return values of getStyles and getPosition are compared to check if they match.

If something is missing please let me know.

**Comment by kentaromiura** [comment]
LGTM but travis failed

**Comment by SergioCrisostomo** [comment]
Travis fails on PhantomJS tests. We could [add a bypass to phantom.js in the specs](https://github.com/mootools/mootools-core/blob/0d83acc0f2dcaf8446ba98b9716145704b963e23/Specs/Element/Element.Style.js#L379) for this.

**Comment by rrelmy** [comment]
The test case has been modified to compare the result of getPosition with the output of getBoundingClientRect.
All tests pass now without testing for PhantomJS

**Pull request merged**
