### PR TITLE
fix mapping of shift onkeypress

### PR DESCRIPTION
**Pull request by SergioCrisostomo**
This is needed for [More's Pseudo Keys](https://github.com/mootools/mootools-more/blob/master/Specs/Element/Element.Event.Pseudos.Keys.js).

### CODE REVIEW

**Comment by arian** [comment]
Seems :+1:

**Comment by arian** [comment]
now https://travis-ci.org/mootools/mootools-more is passing again too :ok_hand:

**Comment by brotherprinter** [comment]
Brother Printer Support
https://www.brotherprintersupport.co.uk/brother-printer-support
https://www.brotherprintersupport.co.uk/canon-printer-support


<a href="https://www.brotherprintersupport.co.uk/brother-printer-support">Brother Printer Tech Support Number</a>
<a href="https://www.brotherprintersupport.co.uk/brother-printer-support">Brother Printer not printing color</a>
<a href="https://www.brotherprintersupport.co.uk/brother-printer-support">Brother Printer help number</a>
<a href="https://www.brotherprintersupport.co.uk/canon-printer-support">Canon Printer tech support number</a>
<a href="https://www.brotherprintersupport.co.uk/canon-printer-support">Canon Printer not printing color</a>
<a href="https://www.brotherprintersupport.co.uk/canon-printer-support">Canon Printer Support help number</a>

Or Call Our Toll Free Number  1-855-992-2337
Sibling Wireless Setup|Learn How To Setup Brother Wireless Printer ?
https://www.brotherprintersupport.co.uk/2019/06/01/sibling-wireless-setuplearn-how-to-setup-brother-wireless-printer/

7 Technical Ways To Fix “Sibling Printer Keeps Going Offline” Without Any Hassle ?
https://www.brotherprintersupport.co.uk/2019/06/01/7-technical-ways-to-fix-sibling-printer-keeps-going-offline-without-any-hassle/

Sibling Printer Driver Is Unavailable | Fix It With Effective Solutions?
https://www.brotherprintersupport.co.uk/2019/06/01/sibling-printer-driver-is-unavailable-fix-it-with-effective-solutions/

**Comment by liamcharles** [comment]
It is an arduous effort to run a small or medium-sized business, and you will require payroll support for sure. It is essential to properly manage and maintain the business account work via payroll customer care. The ideal way to perform these chores is to get the assistance of [QuickBooks payroll support](https://contact-payroll.com/), who can provide 100% customer satisfaction to your company's accounting and financial activity. QuickBooks services have shown their efficiency and reliability in the business account and financial management software. Contact Payroll QuickBooks customer support gives answers for different issue codes. In the successful operation of a company or a business, certain aspects play an essential part, such as payroll help services, and for that, Contact Payroll is the top-notch choice for so many QuickBooks users. Resource management, recording all transactions, prompt payment of bills etc., are some of the most critical functions in a corporate organization that should be appropriately done with QuickBooks payroll support, and you can find everything at our spot! Our website! Contact Payroll!

**Comment by liamcharles** [comment]
Accounting Error Solution is an organization that provides its services to improve QuickBooks Customers' efficiency. Our [QuickBooks Helpline Support](https://accountingerrorsolution.com/contact-quickbooks/) experts have many years of expertise in dealing with a financial business and other challenges to ensure that all problems are solved, and the business is going smoothly and effectively. We understand that companies do not know the importance of how they handle their financial information these days. We also noted that start-ups and small firms typically lose or confront common mistakes in financial data. These mistakes can be remedied only by experts, and our professionals have the expertise and experience in QuickBooks. [Accounting Error Solution](https://accountingerrorsolution.com/) offer outstanding QuickBooks Online Services, which are tailored to your software problems. We support our clients via email, live chat, and call. We are available 24/7 for customer services, and apart from this, if you face any QuickBooks error, you can go through the blogs on our website.

**Pull request merged**
