### PR TITLE
Add Safari 9 in SauceLabs

### PR DESCRIPTION
**Pull request by SergioCrisostomo**
Safari 9 is now available in Sauce Labs.
I noticed they also changed their platform configuration since Safari 8 is now tested with OS `10.10`.

Tested my self and [got green specs](https://travis-ci.org/SergioCrisostomo/mootools-core/builds/87001967).

### CODE REVIEW

**Comment by timwienk** [comment]
Merged in 7300b1c.

**Comment by sophiamoore** [comment]
[best ice shaver](http://besticeshavermachines.com/6-best-undercounter-ice-maker-reviews-in-2018-best-buying-guide/)
[undercounter ice shaver](http://besticeshavermachines.com/6-best-undercounter-ice-maker-reviews-in-2018-best-buying-guide/)

**Comment by sophiamoore** [comment]
[countertop and portable ice shaver ](http://besticeshavermachines.com/7-best-portable-ice-makers-countertop-ice-makers-reviews-in-2018-best-buying-guide/)
[portable ice shaver](http://besticeshavermachines.com/7-best-portable-ice-makers-countertop-ice-makers-reviews-in-2018-best-buying-guide/)
[ice shaver reviews](http://besticeshavermachines.com/7-best-portable-ice-makers-countertop-ice-makers-reviews-in-2018-best-buying-guide/)

**Comment by sophiamoore** [comment]
[commercial ice shaver](http://besticeshavermachines.com/7-best-portable-ice-makers-countertop-ice-makers-reviews-in-2018-best-buying-guide/)
[ice crusher](http://besticeshavermachines.com/7-best-portable-ice-makers-countertop-ice-makers-reviews-in-2018-best-buying-guide/)

**Comment by sophiamoore** [comment]
[block ice crusher machine](http://besticeshavermachines.com/7-best-portable-ice-makers-countertop-ice-makers-reviews-in-2018-best-buying-guide/)
[best commercial ice shaver](http://besticeshavermachines.com/7-best-portable-ice-makers-countertop-ice-makers-reviews-in-2018-best-buying-guide/)

**Comment by sophiamoore** [comment]
[best gelato maker](http://besticeshavermachines.com/7-best-gelato-maker-reviews-in-2018-best-buying-guide/)
[best gelato maker 2018](http://besticeshavermachines.com/7-best-gelato-maker-reviews-in-2018-best-buying-guide/)
[best ice cream maker 2018](http://besticeshavermachines.com/7-best-gelato-maker-reviews-in-2018-best-buying-guide/)

**Comment by sophiamoore** [comment]
[professional ice cream maker](http://besticeshavermachines.com/15-best-ice-shaver-machines-reviews-in-2018-best-buying-guide/)

**Comment by ishibushiUriUri** [comment]
AMAZING !!!!

HERE >>> [ดูบอล](https://www.xn--l3caqb9cizw0iyc1d.com/)

**Pull request closed without merging**
