### PR TITLE
httpOnly cookies

### LINKED ISSUE #2664: [Feature] Cookies for server only via HttpOnly option.
Extend Cookie.write to support `HttpOnly` - https://github.com/mootools/mootools-core/blob/master/Source/Utilities/Cookie.js

eg here: http://jsfiddle.net/ga7pbwrp/

### PR DESCRIPTION
**Pull request by DimitarChristoff**
fixes #2664

### CODE REVIEW

**Comment by payrollqbs** [comment]
[Phone Number For Quickbooks Payroll Support](https://www.payrollsupportphonenumber.com/) +1 800-674-9538 is answered by a group of experts who have complete knowledge of QuickBooks. An accounting software, QuickBooks provides you tools that are immensely beneficial for you. for more visit: https://www.payrollsupportphonenumber.com/

**Comment by payrollqbs** [comment]
With the support of the team at [QuickBooks Desktop Payroll Support Phone Number](https://www.payrollsupportphonenumber.com/quickbooks-payroll-desktop/) +1 800-674-9538, you can overcome the problems that hamper your work. This team comprises of technical support executives who are excellent at their job. for more visit: https://www.payrollsupportphonenumber.com/quickbooks-payroll-desktop/

**Comment by payrollqbs** [comment]
On-time support for QuickBooks is one of the essential parts while using this massive software because you never know when you encounter any error. The team at [QuickBooks POS Support Phone Number](https://www.payrollsupportphonenumber.com/qb-pos/) +1 800-674-9538 takes the responsibility of eliminating each and every issue that comes into the surface in this software. for more visit: https://www.payrollsupportphonenumber.com/qb-pos/

**Comment by tinathomas16** [comment]
Hey,This sound like a great blog and even the presentation look great. You have interesting content that can attract the readers. I even tried writing, but could not make it up to yours. Well, you can utilize the best time for your business, by downloading QuickBooks accounting software. For, those who are new, they can call [QuickBooks Phone Number Support](https://tiny.ee/eA7a
) +1-844-200-2627. The experts will help you with better solutions; they have earned expertise in solving the problem. You can visit the website https://tiny.ee/eA7a

**Comment by tinathomas16** [comment]
Get Comprehensive Support at [Phone Number for QuickBooks Payroll Support ](https://tiny.ee/FvNW)+1-844-200-2627. It is important to change with time. Changes in a positive way bring huge benefits. Gone are those days when you work with paper and pen to maintain a huge file of your payroll.Read More https://tiny.ee/x7Ye & visit our website-https://tiny.ee/5c9A

**Comment by tinathomas16** [comment]
Our excellent support team answers all the calls at our toll-free  [QuickBooks Phone Number](https://tiny.ee/SYF8) +1 844-200-2627.We have experts who have thorough knowledge of QuickBooks and its versions and furnish you with apt solutions. Read More https://tiny.ee/SYF8 & visit our website-https://tiny.ee/ZKqJ

**Comment by tinathomas16** [comment]
Hi, there I went through your content, it’s amazing. I was waiting for such beneficial stuff. Great blogging list! I loved that you picked out a diverse range covering many niches. Anyways, you can also manage your time by downloading QuickBooks accounting software. The experts at [QuickBooks Support Number ](https://tiny.ee/OSG2)+1-844-200-2627 will help you with the best solution. They are available around the clock to assist their users. Whenever you face a problem, you can make an immediate call. For more information, you can visit our website https://tiny.ee/OSG2 & Read More-https://tiny.ee/1eRF

**Pull request merged**
